// docs/.vitepress/components/ROCCurveDemo.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import * as d3 from 'd3'

interface DataPoint {
  score: number
  label: number
}

const svgRef = ref<SVGSVGElement | null>(null)
const threshold = ref(0.5)
const data = ref<DataPoint[]>([])
const rocPoints = ref<Array<[number, number]>>([])
const auc = ref(0)
const confusionMatrix = ref({ tp: 0, fp: 0, tn: 0, fn: 0 })
const currentPoint = ref<[number, number]>([0, 0])
const partialAuc = ref(0)
const isDark = ref(false)

// Detect dark mode
let observer: MutationObserver | null = null

function checkDark() {
  if (typeof document !== 'undefined') {
    isDark.value = document.documentElement.classList.contains('dark')
  }
}

onMounted(() => {
  checkDark()
  observer = new MutationObserver(checkDark)
  observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] })
  generateData()
})

onUnmounted(() => {
  observer?.disconnect()
})

// --- Data generation ---
function normalRandom(mean: number, stdDev: number): number {
  const u1 = Math.random()
  const u2 = Math.random()
  const z0 = Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math.PI * u2)
  return z0 * stdDev + mean
}

function generateData() {
  const points: DataPoint[] = []
  for (let i = 0; i < 100; i++) {
    points.push({ score: Math.max(0, Math.min(1, normalRandom(0.65, 0.15))), label: 1 })
  }
  for (let i = 0; i < 100; i++) {
    points.push({ score: Math.max(0, Math.min(1, normalRandom(0.35, 0.15))), label: 0 })
  }
  data.value = points.sort((a, b) => b.score - a.score)
}

// --- Compute ROC curve from data ---
watch(data, (pts) => {
  if (pts.length === 0) return
  const thresholds = Array.from({ length: 101 }, (_, i) => i / 100)
  const points: Array<[number, number]> = []
  const totalPositive = pts.filter(d => d.label === 1).length
  const totalNegative = pts.filter(d => d.label === 0).length

  thresholds.forEach(thresh => {
    const tp = pts.filter(d => d.score >= thresh && d.label === 1).length
    const fp = pts.filter(d => d.score >= thresh && d.label === 0).length
    points.push([fp / totalNegative, tp / totalPositive])
  })
  points.reverse()
  rocPoints.value = points

  let aucVal = 0
  for (let i = 1; i < points.length; i++) {
    const w = points[i][0] - points[i - 1][0]
    const h = (points[i][1] + points[i - 1][1]) / 2
    aucVal += w * h
  }
  auc.value = aucVal
}, { immediate: true })

// --- Confusion matrix at current threshold ---
watch([data, threshold], () => {
  const pts = data.value
  if (pts.length === 0) return
  const totalPositive = pts.filter(d => d.label === 1).length
  const totalNegative = pts.filter(d => d.label === 0).length
  const tp = pts.filter(d => d.score >= threshold.value && d.label === 1).length
  const fp = pts.filter(d => d.score >= threshold.value && d.label === 0).length
  const tn = pts.filter(d => d.score < threshold.value && d.label === 0).length
  const fn = pts.filter(d => d.score < threshold.value && d.label === 1).length
  confusionMatrix.value = { tp, fp, tn, fn }
  currentPoint.value = [fp / totalNegative, tp / totalPositive]
}, { immediate: true })

// --- Partial AUC ---
watch([currentPoint, rocPoints], () => {
  const rp = rocPoints.value
  if (rp.length === 0) return
  const cp = currentPoint.value
  const idx = rp.findIndex(p => p[0] >= cp[0])
  const partial = rp.slice(0, Math.max(idx, 1))
  if (idx > 0 && idx < rp.length) partial.push(cp)
  let val = 0
  for (let i = 1; i < partial.length; i++) {
    val += (partial[i][0] - partial[i - 1][0]) * (partial[i][1] + partial[i - 1][1]) / 2
  }
  partialAuc.value = val
}, { immediate: true })

// --- Computed metrics ---
const accuracy = computed(() =>
  data.value.length > 0
    ? (confusionMatrix.value.tp + confusionMatrix.value.tn) / data.value.length
    : 0
)
const precision = computed(() => {
  const { tp, fp } = confusionMatrix.value
  return tp + fp > 0 ? tp / (tp + fp) : 0
})
const recall = computed(() => {
  const { tp, fn } = confusionMatrix.value
  return tp + fn > 0 ? tp / (tp + fn) : 0
})
const f1Score = computed(() => {
  const p = precision.value, r = recall.value
  return p + r > 0 ? 2 * p * r / (p + r) : 0
})
const partialPct = computed(() =>
  auc.value > 0 ? (partialAuc.value / auc.value * 100).toFixed(1) : '0.0'
)

// --- Draw ROC chart with D3 ---
function drawChart() {
  if (!svgRef.value || rocPoints.value.length === 0) return
  const dark = isDark.value
  const textColor = dark ? '#e5e7eb' : '#374151'
  const gridColor = dark ? '#ffffff' : '#000000'
  const bgColor = dark ? '#1e1e2e' : '#ffffff'

  const width = 500
  const height = 500
  const margin = { top: 30, right: 30, bottom: 55, left: 55 }
  const innerW = width - margin.left - margin.right
  const innerH = height - margin.top - margin.bottom

  const svg = d3.select(svgRef.value)
  svg.selectAll('*').remove()
  svg.attr('width', width).attr('height', height)

  // Background
  svg.append('rect').attr('width', width).attr('height', height).attr('fill', bgColor).attr('rx', 8)

  const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`)
  const x = d3.scaleLinear().domain([0, 1]).range([0, innerW])
  const y = d3.scaleLinear().domain([0, 1]).range([innerH, 0])

  // Grid
  g.append('g').attr('opacity', 0.08)
    .call(d3.axisLeft(y).tickSize(-innerW).tickFormat(() => ''))
    .selectAll('line').attr('stroke', gridColor)
  g.append('g').attr('opacity', 0.08).attr('transform', `translate(0,${innerH})`)
    .call(d3.axisBottom(x).tickSize(-innerH).tickFormat(() => ''))
    .selectAll('line').attr('stroke', gridColor)

  // Axes
  const xAxis = g.append('g').attr('transform', `translate(0,${innerH})`).call(d3.axisBottom(x))
  xAxis.selectAll('text').attr('fill', textColor)
  xAxis.selectAll('line,path').attr('stroke', textColor)
  g.append('text').attr('x', innerW / 2).attr('y', innerH + 42).attr('text-anchor', 'middle')
    .attr('fill', textColor).attr('font-size', '13px').text('假正例率 (FPR)')

  const yAxis = g.append('g').call(d3.axisLeft(y))
  yAxis.selectAll('text').attr('fill', textColor)
  yAxis.selectAll('line,path').attr('stroke', textColor)
  g.append('text').attr('transform', 'rotate(-90)').attr('x', -innerH / 2).attr('y', -40)
    .attr('text-anchor', 'middle').attr('fill', textColor).attr('font-size', '13px').text('真正例率 (TPR)')

  // Diagonal
  g.append('line').attr('x1', 0).attr('y1', innerH).attr('x2', innerW).attr('y2', 0)
    .attr('stroke', dark ? '#555' : '#aaa').attr('stroke-dasharray', '5,5')

  // AUC area (full)
  const area = d3.area<[number, number]>().x(d => x(d[0])).y0(innerH).y1(d => y(d[1])).curve(d3.curveMonotoneX)
  g.append('path').datum(rocPoints.value).attr('fill', '#3b82f6').attr('opacity', 0.08).attr('d', area)

  // Partial AUC highlight
  const cp = currentPoint.value
  const idx = rocPoints.value.findIndex(p => p[0] >= cp[0])
  const partial = rocPoints.value.slice(0, Math.max(idx, 1))
  if (idx > 0 && idx < rocPoints.value.length) partial.push(cp)
  g.append('path').datum(partial).attr('fill', '#f59e0b').attr('opacity', 0.4).attr('d', area)

  // ROC curve
  const line = d3.line<[number, number]>().x(d => x(d[0])).y(d => y(d[1])).curve(d3.curveMonotoneX)
  g.append('path').datum(rocPoints.value).attr('fill', 'none').attr('stroke', '#3b82f6')
    .attr('stroke-width', 2.5).attr('d', line)

  // Partial curve line
  g.append('path').datum(partial).attr('fill', 'none').attr('stroke', '#f59e0b')
    .attr('stroke-width', 2).attr('d', line)

  // Guide lines from point
  g.append('line').attr('x1', x(cp[0])).attr('y1', y(cp[1])).attr('x2', x(cp[0])).attr('y2', innerH)
    .attr('stroke', '#f59e0b').attr('stroke-dasharray', '3,3').attr('opacity', 0.5)
  g.append('line').attr('x1', x(cp[0])).attr('y1', y(cp[1])).attr('x2', 0).attr('y2', y(cp[1]))
    .attr('stroke', '#f59e0b').attr('stroke-dasharray', '3,3').attr('opacity', 0.5)

  // Current point
  g.append('circle').attr('cx', x(cp[0])).attr('cy', y(cp[1])).attr('r', 6)
    .attr('fill', '#f59e0b').attr('stroke', '#fff').attr('stroke-width', 2)

  // AUC label
  g.append('text').attr('x', innerW - 10).attr('y', 20).attr('text-anchor', 'end')
    .attr('fill', '#3b82f6').attr('font-size', '15px').attr('font-weight', 'bold')
    .text(`AUC = ${auc.value.toFixed(3)}`)
  g.append('text').attr('x', innerW - 10).attr('y', 40).attr('text-anchor', 'end')
    .attr('fill', '#f59e0b').attr('font-size', '13px').attr('font-weight', 'bold')
    .text(`当前面积: ${partialAuc.value.toFixed(3)} (${partialPct.value}%)`)
}

watch([rocPoints, threshold, currentPoint, isDark], drawChart, { flush: 'post' })
</script>

<template>
  <div class="roc-demo">
    <!-- Threshold slider -->
    <div class="slider-row">
      <label class="slider-label">分类阈值: <strong>{{ threshold.toFixed(2) }}</strong></label>
      <input
        type="range" min="0" max="1" step="0.01"
        :value="threshold"
        @input="threshold = Number(($event.target as HTMLInputElement).value)"
        class="slider"
      />
      <div class="slider-ticks"><span>0.00</span><span>1.00</span></div>
    </div>

    <div class="main-grid">
      <!-- SVG chart -->
      <div class="chart-col">
        <svg ref="svgRef" class="chart-svg"></svg>
      </div>

      <!-- Side panel -->
      <div class="side-col">
        <!-- Confusion matrix -->
        <div class="card">
          <h4 class="card-title blue">混淆矩阵</h4>
          <div class="cm-grid">
            <div class="cm-cell green">
              <div class="cm-val">{{ confusionMatrix.tp }}</div>
              <div class="cm-lbl">真正例 (TP)</div>
            </div>
            <div class="cm-cell red">
              <div class="cm-val">{{ confusionMatrix.fp }}</div>
              <div class="cm-lbl">假正例 (FP)</div>
            </div>
            <div class="cm-cell red">
              <div class="cm-val">{{ confusionMatrix.fn }}</div>
              <div class="cm-lbl">假负例 (FN)</div>
            </div>
            <div class="cm-cell green">
              <div class="cm-val">{{ confusionMatrix.tn }}</div>
              <div class="cm-lbl">真负例 (TN)</div>
            </div>
          </div>
        </div>

        <!-- Metrics -->
        <div class="card">
          <h4 class="card-title blue">评估指标</h4>
          <div class="metric-list">
            <div class="metric-row"><span>准确率 (Accuracy)</span><strong>{{ (accuracy * 100).toFixed(1) }}%</strong></div>
            <div class="metric-row"><span>精确率 (Precision)</span><strong>{{ (precision * 100).toFixed(1) }}%</strong></div>
            <div class="metric-row"><span>召回率 (Recall/TPR)</span><strong>{{ (recall * 100).toFixed(1) }}%</strong></div>
            <div class="metric-row"><span>F1 分数</span><strong>{{ (f1Score * 100).toFixed(1) }}%</strong></div>
            <div class="metric-row sep"><span>FPR</span><strong>{{ (currentPoint[0] * 100).toFixed(1) }}%</strong></div>
          </div>
        </div>

        <!-- Area comparison -->
        <div class="card highlight-card">
          <h4 class="card-title amber">面积对比</h4>
          <div class="bar-group">
            <div class="bar-label"><span class="text-blue">完整 AUC</span><strong>{{ auc.toFixed(3) }}</strong></div>
            <div class="bar-track"><div class="bar-fill blue-bg" style="width:100%"></div></div>
          </div>
          <div class="bar-group">
            <div class="bar-label"><span class="text-amber">当前累积面积</span><strong>{{ partialAuc.toFixed(3) }}</strong></div>
            <div class="bar-track"><div class="bar-fill amber-bg" :style="{ width: partialPct + '%' }"></div></div>
            <div class="bar-pct">{{ partialPct }}% of total</div>
          </div>
          <p class="bar-hint">💡 拖动阈值滑块，观察黄色进度条的变化！</p>
        </div>
      </div>
    </div>

    <!-- Explanation notes -->
    <div class="notes">
      <p><strong class="text-blue">完整 AUC</strong>：整条 ROC 曲线下方的蓝色半透明区域，表示模型在所有阈值下的综合性能。当前 AUC = {{ auc.toFixed(3) }}</p>
      <p><strong class="text-amber">橙色高亮区域</strong>：从起点 (0,0) 到当前操作点的部分面积。调整阈值滑块，观察橙色区域如何动态变化！</p>
      <p><strong class="text-amber">橙色圆点</strong>：表示当前阈值下的操作点 (FPR, TPR)，对应右侧混淆矩阵的统计结果</p>
      <p class="hint">💡 提示：降低阈值 → 更多样本被预测为正类 → FPR 和 TPR 同时增加 → 操作点向右上方移动</p>
    </div>
  </div>
</template>

<style scoped>
.roc-demo {
  border: 1px solid var(--vp-c-divider);
  border-radius: 12px;
  padding: 24px;
  background: var(--vp-c-bg-soft);
  margin: 16px 0;
}

/* Slider */
.slider-row { margin-bottom: 20px; }
.slider-label { display: block; font-size: 14px; margin-bottom: 6px; color: var(--vp-c-text-1); }
.slider { width: 100%; accent-color: #3b82f6; }
.slider-ticks { display: flex; justify-content: space-between; font-size: 12px; color: var(--vp-c-text-3); margin-top: 2px; }

/* Layout */
.main-grid { display: grid; grid-template-columns: 1fr; gap: 20px; }
@media (min-width: 768px) { .main-grid { grid-template-columns: 3fr 2fr; } }
.chart-col { display: flex; justify-content: center; overflow-x: auto; }
.chart-svg { border-radius: 8px; max-width: 100%; height: auto; }
.side-col { display: flex; flex-direction: column; gap: 16px; }

/* Cards */
.card {
  background: var(--vp-c-bg);
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  padding: 16px;
}
.card-title { font-size: 15px; font-weight: 600; margin: 0 0 12px 0; }
.card-title.blue { color: #3b82f6; }
.card-title.amber { color: #d97706; }

/* Confusion matrix grid */
.cm-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; text-align: center; }
.cm-cell { padding: 10px 6px; border-radius: 6px; border: 1px solid; }
.cm-cell.green { background: rgba(34,197,94,0.08); border-color: rgba(34,197,94,0.4); }
.cm-cell.red { background: rgba(239,68,68,0.08); border-color: rgba(239,68,68,0.4); }
.cm-val { font-size: 20px; font-weight: 700; }
.cm-cell.green .cm-val { color: #16a34a; }
.cm-cell.red .cm-val { color: #dc2626; }
.cm-lbl { font-size: 11px; color: var(--vp-c-text-2); margin-top: 2px; }

/* Metrics */
.metric-list { font-size: 13px; }
.metric-row { display: flex; justify-content: space-between; padding: 4px 0; color: var(--vp-c-text-1); }
.metric-row.sep { border-top: 1px solid var(--vp-c-divider); margin-top: 4px; padding-top: 8px; }

/* Highlight card */
.highlight-card { border-color: #d97706; }
.bar-group { margin-bottom: 12px; }
.bar-label { display: flex; justify-content: space-between; font-size: 13px; margin-bottom: 4px; color: var(--vp-c-text-1); }
.bar-track { height: 20px; background: var(--vp-c-bg-soft); border-radius: 4px; overflow: hidden; }
.bar-fill { height: 100%; transition: width 0.3s; border-radius: 4px; }
.blue-bg { background: #3b82f6; }
.amber-bg { background: #f59e0b; }
.bar-pct { text-align: right; font-size: 11px; color: var(--vp-c-text-3); margin-top: 2px; }
.bar-hint { font-size: 12px; color: var(--vp-c-text-3); font-style: italic; margin: 8px 0 0; border-top: 1px solid var(--vp-c-divider); padding-top: 8px; }

/* Notes */
.notes { margin-top: 20px; font-size: 13px; color: var(--vp-c-text-2); }
.notes p { margin: 6px 0; line-height: 1.6; }
.notes .hint { font-size: 12px; font-style: italic; color: var(--vp-c-text-3); margin-top: 10px; }

/* Color helpers */
.text-blue { color: #3b82f6; }
.text-amber { color: #d97706; }

/* Dark mode metric cell tweaks */
:global(.dark) .cm-cell.green { background: rgba(34,197,94,0.12); }
:global(.dark) .cm-cell.red { background: rgba(239,68,68,0.12); }
:global(.dark) .cm-cell.green .cm-val { color: #4ade80; }
:global(.dark) .cm-cell.red .cm-val { color: #f87171; }
</style>

// src/components/visualizations/ROCCurveDemo.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import * as d3 from 'd3'

interface DataPoint {
  score: number
  label: number
}

export function ROCCurveDemo() {
  const svgRef = useRef<SVGSVGElement>(null)
  const [threshold, setThreshold] = useState(0.5)
  const [data, setData] = useState<DataPoint[]>([])
  const [rocPoints, setRocPoints] = useState<Array<[number, number]>>([])
  const [auc, setAuc] = useState(0)

  // 生成模拟数据（使用正态分布，确保有重叠）
  useEffect(() => {
    const generateData = () => {
      const points: DataPoint[] = []
      
      // 正态分布随机数生成器 (Box-Muller 变换)
      const normalRandom = (mean: number, stdDev: number) => {
        const u1 = Math.random()
        const u2 = Math.random()
        const z0 = Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math.PI * u2)
        return z0 * stdDev + mean
      }
      
      // 正类（label=1）：分数偏高，均值0.65，标准差0.15
      for (let i = 0; i < 100; i++) {
        const score = Math.max(0, Math.min(1, normalRandom(0.65, 0.15)))
        points.push({ score, label: 1 })
      }
      
      // 负类（label=0）：分数偏低，均值0.35，标准差0.15
      for (let i = 0; i < 100; i++) {
        const score = Math.max(0, Math.min(1, normalRandom(0.35, 0.15)))
        points.push({ score, label: 0 })
      }
      
      return points.sort((a, b) => b.score - a.score)
    }
    setData(generateData())
  }, [])

  // 计算 ROC 曲线点
  useEffect(() => {
    if (data.length === 0) return

    const thresholds = Array.from({ length: 101 }, (_, i) => i / 100)
    const points: Array<[number, number]> = []
    
    const totalPositive = data.filter(d => d.label === 1).length
    const totalNegative = data.filter(d => d.label === 0).length

    thresholds.forEach(thresh => {
      const tp = data.filter(d => d.score >= thresh && d.label === 1).length
      const fp = data.filter(d => d.score >= thresh && d.label === 0).length
      
      const tpr = tp / totalPositive
      const fpr = fp / totalNegative
      
      points.push([fpr, tpr])
    })

    // 反转顺序：从 (0,0) 到 (1,1)，确保 FPR 递增
    points.reverse()

    setRocPoints(points)

    // 计算 AUC（梯形法则）
    let aucValue = 0
    for (let i = 1; i < points.length; i++) {
      const width = points[i][0] - points[i - 1][0]
      const height = (points[i][1] + points[i - 1][1]) / 2
      aucValue += width * height
    }
    setAuc(aucValue)
  }, [data])

  // 计算当前阈值下的混淆矩阵
  const [confusionMatrix, setConfusionMatrix] = useState({ tp: 0, fp: 0, tn: 0, fn: 0 })
  const [currentPoint, setCurrentPoint] = useState<[number, number]>([0, 0])

  useEffect(() => {
    if (data.length === 0) return

    const totalPositive = data.filter(d => d.label === 1).length
    const totalNegative = data.filter(d => d.label === 0).length

    const tp = data.filter(d => d.score >= threshold && d.label === 1).length
    const fp = data.filter(d => d.score >= threshold && d.label === 0).length
    const tn = data.filter(d => d.score < threshold && d.label === 0).length
    const fn = data.filter(d => d.score < threshold && d.label === 1).length

    setConfusionMatrix({ tp, fp, tn, fn })

    const tpr = tp / totalPositive
    const fpr = fp / totalNegative
    setCurrentPoint([fpr, tpr])
  }, [data, threshold])

  // 绘制 ROC 曲线
  useEffect(() => {
    if (!svgRef.current || rocPoints.length === 0) return

    const width = 600
    const height = 600
    const margin = { top: 40, right: 40, bottom: 60, left: 60 }

    const svg = d3.select(svgRef.current)
    svg.selectAll('*').remove()

    const g = svg
      .attr('width', width)
      .attr('height', height)
      .append('g')
      .attr('transform', `translate(${margin.left},${margin.top})`)

    const innerWidth = width - margin.left - margin.right
    const innerHeight = height - margin.top - margin.bottom

    // 坐标轴
    const xScale = d3.scaleLinear().domain([0, 1]).range([0, innerWidth])
    const yScale = d3.scaleLinear().domain([0, 1]).range([innerHeight, 0])

    // X 轴
    g.append('g')
      .attr('transform', `translate(0,${innerHeight})`)
      .call(d3.axisBottom(xScale))
      .selectAll('text')
      .attr('fill', '#FFFFFF')

    g.append('text')
      .attr('x', innerWidth / 2)
      .attr('y', innerHeight + 45)
      .attr('text-anchor', 'middle')
      .attr('fill', '#FFFFFF')
      .text('假正例率 (FPR)')

    // Y 轴
    g.append('g')
      .call(d3.axisLeft(yScale))
      .selectAll('text')
      .attr('fill', '#FFFFFF')

    g.append('text')
      .attr('transform', 'rotate(-90)')
      .attr('x', -innerHeight / 2)
      .attr('y', -45)
      .attr('text-anchor', 'middle')
      .attr('fill', '#FFFFFF')
      .text('真正例率 (TPR)')

    // 网格线
    g.append('g')
      .attr('class', 'grid')
      .attr('opacity', 0.1)
      .call(d3.axisLeft(yScale).tickSize(-innerWidth).tickFormat(() => ''))
      .selectAll('line')
      .attr('stroke', '#FFFFFF')

    g.append('g')
      .attr('class', 'grid')
      .attr('transform', `translate(0,${innerHeight})`)
      .attr('opacity', 0.1)
      .call(d3.axisBottom(xScale).tickSize(-innerHeight).tickFormat(() => ''))
      .selectAll('line')
      .attr('stroke', '#FFFFFF')

    // 对角线（随机猜测）
    g.append('line')
      .attr('x1', 0)
      .attr('y1', innerHeight)
      .attr('x2', innerWidth)
      .attr('y2', 0)
      .attr('stroke', '#666')
      .attr('stroke-dasharray', '5,5')
      .attr('stroke-width', 1)

    // ROC 曲线
    const line = d3.line<[number, number]>()
      .x(d => xScale(d[0]))
      .y(d => yScale(d[1]))
      .curve(d3.curveMonotoneX)

    const path = g.append('path')
      .datum(rocPoints)
      .attr('fill', 'none')
      .attr('stroke', '#58C4DD')
      .attr('stroke-width', 3)
      .attr('d', line)

    // 动画效果
    const totalLength = path.node()?.getTotalLength() || 0
    path
      .attr('stroke-dasharray', `${totalLength} ${totalLength}`)
      .attr('stroke-dashoffset', totalLength)
      .transition()
      .duration(2000)
      .attr('stroke-dashoffset', 0)

    // AUC 区域填充（整个曲线下方，低透明度）
    const area = d3.area<[number, number]>()
      .x(d => xScale(d[0]))
      .y0(innerHeight)
      .y1(d => yScale(d[1]))
      .curve(d3.curveMonotoneX)

    g.append('path')
      .datum(rocPoints)
      .attr('fill', '#58C4DD')
      .attr('opacity', 0.05)
      .attr('d', area)

    // 动态高亮：从起点到当前操作点的部分面积
    const currentIndex = rocPoints.findIndex(p => p[0] >= currentPoint[0])
    const partialPoints = rocPoints.slice(0, Math.max(currentIndex, 1))
    // 添加当前操作点，确保精确到当前阈值
    if (currentIndex > 0 && currentIndex < rocPoints.length) {
      partialPoints.push(currentPoint)
    }

    // 橙色高亮区域（更高透明度）
    g.append('path')
      .datum(partialPoints)
      .attr('fill', '#F59E0B')
      .attr('opacity', 0.5)
      .attr('d', area)
      .transition()
      .duration(300)

    // 添加橙色边框，使区域更明显
    const partialLine = d3.line<[number, number]>()
      .x(d => xScale(d[0]))
      .y(d => yScale(d[1]))
      .curve(d3.curveMonotoneX)

    g.append('path')
      .datum(partialPoints)
      .attr('fill', 'none')
      .attr('stroke', '#F59E0B')
      .attr('stroke-width', 2)
      .attr('d', partialLine)
      .transition()
      .duration(300)

    // 计算部分 AUC（从起点到当前操作点）
    let partialAuc = 0
    for (let i = 1; i < partialPoints.length; i++) {
      const width = partialPoints[i][0] - partialPoints[i - 1][0]
      const height = (partialPoints[i][1] + partialPoints[i - 1][1]) / 2
      partialAuc += width * height
    }

    // 添加部分 AUC 文本标注（更大、更醒目）
    g.append('text')
      .attr('x', innerWidth - 120)
      .attr('y', 55)
      .attr('fill', '#F59E0B')
      .attr('font-size', '16px')
      .attr('font-weight', 'bold')
      .text(`当前面积: ${partialAuc.toFixed(3)}`)

    // 添加百分比显示
    const percentage = (partialAuc / auc * 100).toFixed(1)
    g.append('text')
      .attr('x', innerWidth - 120)
      .attr('y', 75)
      .attr('fill', '#F59E0B')
      .attr('font-size', '14px')
      .text(`(${percentage}% of total)`)

    // 当前操作点（根据阈值）
    g.append('circle')
      .attr('cx', xScale(currentPoint[0]))
      .attr('cy', yScale(currentPoint[1]))
      .attr('r', 6)
      .attr('fill', '#F59E0B')
      .attr('stroke', '#FFFFFF')
      .attr('stroke-width', 2)

    // 从操作点到坐标轴的辅助线
    g.append('line')
      .attr('x1', xScale(currentPoint[0]))
      .attr('y1', yScale(currentPoint[1]))
      .attr('x2', xScale(currentPoint[0]))
      .attr('y2', innerHeight)
      .attr('stroke', '#F59E0B')
      .attr('stroke-dasharray', '3,3')
      .attr('stroke-width', 1)
      .attr('opacity', 0.6)

    g.append('line')
      .attr('x1', xScale(currentPoint[0]))
      .attr('y1', yScale(currentPoint[1]))
      .attr('x2', 0)
      .attr('y2', yScale(currentPoint[1]))
      .attr('stroke', '#F59E0B')
      .attr('stroke-dasharray', '3,3')
      .attr('stroke-width', 1)
      .attr('opacity', 0.6)

    // AUC 文本
    g.append('text')
      .attr('x', innerWidth - 80)
      .attr('y', 30)
      .attr('fill', '#58C4DD')
      .attr('font-size', '18px')
      .attr('font-weight', 'bold')
      .text(`AUC = ${auc.toFixed(3)}`)

  }, [rocPoints, auc, threshold, currentPoint])

  // 计算评估指标
  const accuracy = data.length > 0
    ? (confusionMatrix.tp + confusionMatrix.tn) / data.length
    : 0
  const precision = (confusionMatrix.tp + confusionMatrix.fp) > 0
    ? confusionMatrix.tp / (confusionMatrix.tp + confusionMatrix.fp)
    : 0
  const recall = (confusionMatrix.tp + confusionMatrix.fn) > 0
    ? confusionMatrix.tp / (confusionMatrix.tp + confusionMatrix.fn)
    : 0
  const f1Score = (precision + recall) > 0
    ? 2 * (precision * recall) / (precision + recall)
    : 0

  // 计算部分 AUC（用于右侧面板显示）
  const [partialAuc, setPartialAuc] = useState(0)
  useEffect(() => {
    if (rocPoints.length === 0) return
    const currentIndex = rocPoints.findIndex(p => p[0] >= currentPoint[0])
    const partialPoints = rocPoints.slice(0, Math.max(currentIndex, 1))
    if (currentIndex > 0 && currentIndex < rocPoints.length) {
      partialPoints.push(currentPoint)
    }
    let partial = 0
    for (let i = 1; i < partialPoints.length; i++) {
      const width = partialPoints[i][0] - partialPoints[i - 1][0]
      const height = (partialPoints[i][1] + partialPoints[i - 1][1]) / 2
      partial += width * height
    }
    setPartialAuc(partial)
  }, [currentPoint, rocPoints])

  return (
    <div className="bg-ml-bg-secondary p-6 rounded-lg">
      {/* 控制面板 */}
      <div className="mb-6">
        <label className="block text-sm font-medium mb-2">
          分类阈值: {threshold.toFixed(2)}
        </label>
        <input
          type="range"
          min="0"
          max="1"
          step="0.01"
          value={threshold}
          onChange={(e) => setThreshold(Number(e.target.value))}
          className="w-full accent-ml-blue"
        />
        <div className="flex justify-between text-xs text-white mt-1">
          <span>0.00</span>
          <span>1.00</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* ROC 曲线图 */}
        <div className="lg:col-span-2">
          <div className="flex justify-center">
            <svg ref={svgRef} className="bg-ml-bg-dark rounded" />
          </div>
        </div>

        {/* 右侧信息面板 */}
        <div className="space-y-4">
          {/* 混淆矩阵 */}
          <div className="bg-ml-bg-dark p-4 rounded-lg">
            <h3 className="text-lg font-semibold mb-3 text-ml-blue">混淆矩阵</h3>
            <div className="grid grid-cols-2 gap-2 text-center text-sm">
              <div className="bg-green-900/30 border border-green-500 p-3 rounded">
                <div className="text-green-400 font-bold text-xl">{confusionMatrix.tp}</div>
                <div className="text-xs text-white">真正例 (TP)</div>
              </div>
              <div className="bg-red-900/30 border border-red-500 p-3 rounded">
                <div className="text-red-400 font-bold text-xl">{confusionMatrix.fp}</div>
                <div className="text-xs text-white">假正例 (FP)</div>
              </div>
              <div className="bg-red-900/30 border border-red-500 p-3 rounded">
                <div className="text-red-400 font-bold text-xl">{confusionMatrix.fn}</div>
                <div className="text-xs text-white">假负例 (FN)</div>
              </div>
              <div className="bg-green-900/30 border border-green-500 p-3 rounded">
                <div className="text-green-400 font-bold text-xl">{confusionMatrix.tn}</div>
                <div className="text-xs text-white">真负例 (TN)</div>
              </div>
            </div>
          </div>

          {/* 评估指标 */}
          <div className="bg-ml-bg-dark p-4 rounded-lg">
            <h3 className="text-lg font-semibold mb-3 text-ml-blue">评估指标</h3>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-white">准确率 (Accuracy):</span>
                <span className="text-white font-bold">{(accuracy * 100).toFixed(1)}%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-white">精确率 (Precision):</span>
                <span className="text-white font-bold">{(precision * 100).toFixed(1)}%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-white">召回率 (Recall/TPR):</span>
                <span className="text-white font-bold">{(recall * 100).toFixed(1)}%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-white">F1 分数:</span>
                <span className="text-white font-bold">{(f1Score * 100).toFixed(1)}%</span>
              </div>
              <div className="flex justify-between border-t border-gray-700 pt-2 mt-2">
                <span className="text-white">FPR:</span>
                <span className="text-white font-bold">{(currentPoint[0] * 100).toFixed(1)}%</span>
              </div>
            </div>
          </div>

          {/* 当前操作点 */}
          <div className="bg-ml-bg-dark p-4 rounded-lg">
            <h3 className="text-lg font-semibold mb-2 text-yellow-500">当前操作点</h3>
            <div className="text-sm space-y-1">
              <p className="text-white">
                TPR: <span className="text-white font-bold">{(currentPoint[1] * 100).toFixed(1)}%</span>
              </p>
              <p className="text-white">
                FPR: <span className="text-white font-bold">{(currentPoint[0] * 100).toFixed(1)}%</span>
              </p>
            </div>
          </div>

          {/* 面积对比可视化 */}
          <div className="bg-ml-bg-dark p-4 rounded-lg border-2 border-yellow-500">
            <h3 className="text-lg font-semibold mb-3 text-yellow-500">面积对比</h3>
            <div className="space-y-3">
              {/* 完整 AUC */}
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-cyan-400">完整 AUC</span>
                  <span className="text-white font-bold">{auc.toFixed(3)}</span>
                </div>
                <div className="w-full h-6 bg-gray-700 rounded overflow-hidden">
                  <div 
                    className="h-full bg-cyan-500 transition-all duration-300"
                    style={{ width: '100%' }}
                  />
                </div>
              </div>

              {/* 当前部分面积 */}
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-yellow-500">当前累积面积</span>
                  <span className="text-white font-bold">{partialAuc.toFixed(3)}</span>
                </div>
                <div className="w-full h-6 bg-gray-700 rounded overflow-hidden">
                  <div 
                    className="h-full bg-yellow-500 transition-all duration-300"
                    style={{ width: `${(partialAuc / auc * 100)}%` }}
                  />
                </div>
                <p className="text-xs text-gray-400 mt-1 text-right">
                  {(partialAuc / auc * 100).toFixed(1)}% of total
                </p>
              </div>

              <p className="text-xs text-gray-300 italic pt-2 border-t border-gray-700">
                💡 拖动阈值滑块，观察黄色进度条的变化！
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* 说明文字 */}
      <div className="mt-6 text-sm text-white space-y-2">
        <p>
          <strong className="text-ml-blue">完整 AUC</strong>:
          整条 ROC 曲线下方的蓝色半透明区域，表示模型在所有阈值下的综合性能。当前 AUC = {auc.toFixed(3)}
        </p>
        <p>
          <strong className="text-ml-yellow">橙色高亮区域</strong>:
          从起点 (0,0) 到当前操作点的部分面积。调整阈值滑块，观察橙色区域如何动态变化！
        </p>
        <p>
          <strong className="text-ml-yellow">橙色圆点</strong>:
          表示当前阈值下的操作点 (FPR, TPR)，对应右侧混淆矩阵的统计结果
        </p>
        <p>
          <strong className="text-white">灰色虚线</strong>:
          表示随机猜测的性能基线（AUC = 0.5）
        </p>
        <p className="text-xs text-gray-400 italic">
          💡 提示：降低阈值 → 更多样本被预测为正类 → FPR 和 TPR 同时增加 → 操作点向右上方移动
        </p>
      </div>
    </div>
  )
}
